version: "3.7"

services:
  dash-test:
    build:
      context: .
      target: tester

  dash-app:
    build:
      context: .
      target: prod
    ports:
      - 8080:8050
    healthcheck:
      test: "curl --fail http://localhost:8050/ping"