version: "3.7"

services:
  streamlit-test:
    build:
      context: .
      target: tester

  streamlit-app:
    build:
      context: .
      target: prod
    ports:
      - 8080:8501
    healthcheck:
      test: "curl --fail http://localhost:8501/_stcore/health"