name: Python application

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: azure terraform checks
      working-directory: ./deployment/
      run: |
        for terraform_dir in $(find . -type f -name 'main.tf' | sed -r 's|/[^/]+$||' |sort |uniq)
        do
          terraform -chdir=${terraform_dir} init --backend=false
          terraform -chdir=${terraform_dir} fmt --check --diff
        done
    - name: docker streamlit build
      working-directory: ./services/streamlit/
      run: |
        docker-compose build streamlit-test
    - name: run streamlit image in container
      working-directory: ./services/streamlit/
      run: |
        docker-compose up --build --detach
        sleep 1
        curl http://localhost:8080
        docker-compose down
    - name: docker dash build
      working-directory: ./services/dash/
      run: |
        docker-compose build dash-test
    - name: run dash image in container
      working-directory: ./services/dash/
      run: |
        docker-compose up --build --detach
        sleep 1
        curl http://localhost:8080
        docker-compose down
    - name: docker shiny build
      working-directory: ./services/shiny/
      run: |
        docker-compose build shiny-test
    - name: run shiny image in container
      working-directory: ./services/shiny/
      run: |
        docker-compose up --build --detach
        sleep 1
        curl http://localhost:8080
        docker-compose down
